### ISSUE TITLE
/back bug after using /spawn

### ISSUE THREAD

**Issue by ghost** [schlatt-co/CowBot#6]
When you do /spawn then do /back, you don't go to your last tp but to the tp before your last one.

[https://youtu.be/pWW9ZkMzrFs ](video proof)

Maybe I'm a dumbass and this is how its supposed to be but it drives me crazy.

**Comment by JRoy** [comment]
ugh essentials, I'll fix this maybe

**Comment by JRoy** [comment]
Fixed in 9db4e680bcb3b735489c6fe9356bf317666ed7d0
